### ISSUE TITLE
无法在模块 iptables 打开时使用 tailscale

### ISSUE THREAD

**Issue by MCSeekeri** [twoone-3/AdGuardHomeForRoot#10]
只要模块处于启用状态且 iptables 规则打开，tailscale 启动 VPN 连接的时候就会出错，但其他 VPN 软件正常工作。
/data/adb/agh/bin 内的日志没有有效记录。

目前不确定错误原因，可能与 tailscale 同时会接管 DNS 解析有关。

**Comment by twoone-3** [comment]
尝试把config.sh的ipv6改为true,注意在模块关闭的时候改

MCSeekeri ***@***.***> 于 2024年11月15日周五 11:05写道：
